export const deviceTypeList = [
    {
        deviceType: '雨滴谱仪',
        deviceTypeId: 1,
        devices: [
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 36.29,
                deviceId: 1,
                deviceName: '馆陶王桥乡火箭',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邯郸市/馆陶县',
                contact: '彭丽彬',
                areaDistrict: 130433,
                offlineTime: 20,
                installMode: '固定',
                height: 41,
                intervalTime: 5,
                longitude: 115.15,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4096',
                establishDate: '2016-01-01',
                areaCity: 130400,
                ppeType: '当地',
                areaCode: 130433,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 36.3925,
                deviceId: 2,
                deviceName: '磁县老观测场',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邯郸市/磁县',
                contact: '彭丽彬',
                areaDistrict: 130427,
                offlineTime: 20,
                installMode: '固定',
                height: 70,
                intervalTime: 5,
                longitude: 114.32,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4090',
                establishDate: '2016-01-01',
                areaCity: 130400,
                ppeType: '当地',
                areaCode: 130427,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 36.61833,
                deviceId: 3,
                deviceName: '涉县下温村火箭作业点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邯郸市/涉县',
                contact: '彭丽彬',
                areaDistrict: 130426,
                offlineTime: 20,
                installMode: '固定',
                height: 470,
                intervalTime: 5,
                longitude: 113.6,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4044',
                establishDate: '2016-01-01',
                areaCity: 130400,
                ppeType: '当地',
                areaCode: 130426,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 36.82556,
                deviceId: 4,
                deviceName: '武安苏庄高炮',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邯郸市/',
                contact: '彭丽彬',
                areaDistrict: 0,
                offlineTime: 20,
                installMode: '固定',
                height: 280,
                intervalTime: 5,
                longitude: 113.99,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '3195',
                establishDate: '2016-01-01',
                areaCity: 130400,
                ppeType: '当地',
                areaCode: 0,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 36.48,
                deviceId: 5,
                deviceName: '广平县',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邯郸市/广平县',
                contact: '彭丽彬',
                areaDistrict: 130432,
                offlineTime: 20,
                installMode: '固定',
                height: 49,
                intervalTime: 5,
                longitude: 114.96,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4126',
                establishDate: '2016-01-01',
                areaCity: 130400,
                ppeType: '当地',
                areaCode: 130432,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 36.70056,
                deviceId: 6,
                deviceName: '曲周白寨火箭',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邯郸市/曲周县',
                contact: '彭丽彬',
                areaDistrict: 130435,
                offlineTime: 20,
                installMode: '固定',
                height: 40,
                intervalTime: 5,
                longitude: 114.92,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4072',
                establishDate: '2016-01-01',
                areaCity: 130400,
                ppeType: '当地',
                areaCode: 130435,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 36.52,
                deviceId: 7,
                deviceName: '肥乡南河马台火箭',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邯郸市/',
                contact: '彭丽彬',
                areaDistrict: 0,
                offlineTime: 20,
                installMode: '固定',
                height: 50,
                intervalTime: 5,
                longitude: 114.77,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4078',
                establishDate: '2016-01-01',
                areaCity: 130400,
                ppeType: '当地',
                areaCode: 0,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 36.53,
                deviceId: 8,
                deviceName: '魏县元堡乡火箭',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邯郸市/魏县',
                contact: '彭丽彬',
                areaDistrict: 130434,
                offlineTime: 20,
                installMode: '固定',
                height: 50,
                intervalTime: 5,
                longitude: 114.812,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4087',
                establishDate: '2016-01-01',
                areaCity: 130400,
                ppeType: '当地',
                areaCode: 130434,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 36.76389,
                deviceId: 9,
                deviceName: '武安阳邑智寿园高炮',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邯郸市/',
                contact: '彭丽彬',
                areaDistrict: 0,
                offlineTime: 20,
                installMode: '固定',
                height: 280,
                intervalTime: 5,
                longitude: 113.89,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4138',
                establishDate: '2016-01-01',
                areaCity: 130400,
                ppeType: '当地',
                areaCode: 0,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 36.91472,
                deviceId: 10,
                deviceName: '鸡泽隍营村火箭',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邯郸市/鸡泽县',
                contact: '彭丽彬',
                areaDistrict: 130431,
                offlineTime: 20,
                installMode: '固定',
                height: 36,
                intervalTime: 5,
                longitude: 114.83,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4047',
                establishDate: '2016-01-01',
                areaCity: 130400,
                ppeType: '当地',
                areaCode: 130431,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 36.78,
                deviceId: 11,
                deviceName: '峰峰王看',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邯郸市/',
                contact: '彭丽彬',
                areaDistrict: 0,
                offlineTime: 20,
                installMode: '固定',
                height: 149,
                intervalTime: 5,
                longitude: 114.49,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4104',
                establishDate: '2016-01-01',
                areaCity: 130400,
                ppeType: '当地',
                areaCode: 0,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 36.81694,
                deviceId: 12,
                deviceName: '邱县新马头镇火箭',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邯郸市/邱县',
                contact: '彭丽彬',
                areaDistrict: 130430,
                offlineTime: 20,
                installMode: '固定',
                height: 37,
                intervalTime: 5,
                longitude: 115.22,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4003',
                establishDate: '2016-01-01',
                areaCity: 130400,
                ppeType: '当地',
                areaCode: 130430,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.63416,
                deviceId: 13,
                deviceName: '高邑县',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/石家庄市/高邑县',
                contact: '彭丽彬',
                areaDistrict: 130127,
                offlineTime: 20,
                installMode: '固定',
                height: 49,
                intervalTime: 5,
                longitude: 114.60694,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4201',
                establishDate: '2016-01-01',
                areaCity: 130100,
                ppeType: '当地',
                areaCode: 130127,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.7944,
                deviceId: 14,
                deviceName: '赵县南庄',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/石家庄市/赵县',
                contact: '彭丽彬',
                areaDistrict: 130133,
                offlineTime: 20,
                installMode: '固定',
                height: 39,
                intervalTime: 5,
                longitude: 114.78,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4219',
                establishDate: '2016-01-01',
                areaCity: 130100,
                ppeType: '当地',
                areaCode: 130133,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.90361,
                deviceId: 15,
                deviceName: '栾城区',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/石家庄市/栾城区',
                contact: '彭丽彬',
                areaDistrict: 130111,
                offlineTime: 20,
                installMode: '固定',
                height: 60,
                intervalTime: 5,
                longitude: 114.61111,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4153',
                establishDate: '2016-01-01',
                areaCity: 130100,
                ppeType: '当地',
                areaCode: 130111,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.834,
                deviceId: 16,
                deviceName: '赵县农科所',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/石家庄市/赵县',
                contact: '彭丽彬',
                areaDistrict: 130133,
                offlineTime: 20,
                installMode: '固定',
                height: 39,
                intervalTime: 5,
                longitude: 114.818,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4120',
                establishDate: '2016-01-01',
                areaCity: 130100,
                ppeType: '当地',
                areaCode: 130133,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.843,
                deviceId: 17,
                deviceName: '井陉县景庄村',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/石家庄市/井陉县',
                contact: '彭丽彬',
                areaDistrict: 130121,
                offlineTime: 20,
                installMode: '固定',
                height: 256,
                intervalTime: 5,
                longitude: 114.062,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4085',
                establishDate: '2016-01-01',
                areaCity: 130100,
                ppeType: '当地',
                areaCode: 130121,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.039,
                deviceId: 18,
                deviceName: '晋州',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/石家庄市/晋州市',
                contact: '彭丽彬',
                areaDistrict: 130183,
                offlineTime: 20,
                installMode: '固定',
                height: 42,
                intervalTime: 5,
                longitude: 115.05,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4195',
                establishDate: '2016-01-01',
                areaCity: 130100,
                ppeType: '当地',
                areaCode: 130183,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.45,
                deviceId: 19,
                deviceName: '灵寿县徐家水库',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/石家庄市/灵寿县',
                contact: '彭丽彬',
                areaDistrict: 130126,
                offlineTime: 20,
                installMode: '固定',
                height: 109,
                intervalTime: 5,
                longitude: 114.28,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4199',
                establishDate: '2016-01-01',
                areaCity: 130100,
                ppeType: '当地',
                areaCode: 130126,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.2278,
                deviceId: 20,
                deviceName: '正定县',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/石家庄市/正定县',
                contact: '彭丽彬',
                areaDistrict: 130123,
                offlineTime: 20,
                installMode: '固定',
                height: 71,
                intervalTime: 5,
                longitude: 114.521,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4218',
                establishDate: '2016-01-01',
                areaCity: 130100,
                ppeType: '当地',
                areaCode: 130123,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.61,
                deviceId: 21,
                deviceName: '行唐县口头水库',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/石家庄市/行唐县',
                contact: '彭丽彬',
                areaDistrict: 130125,
                offlineTime: 20,
                installMode: '固定',
                height: 96,
                intervalTime: 5,
                longitude: 114.38,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4203',
                establishDate: '2016-01-01',
                areaCity: 130100,
                ppeType: '当地',
                areaCode: 130125,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.21,
                deviceId: 22,
                deviceName: '无极县东侯坊',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/石家庄市/无极县',
                contact: '彭丽彬',
                areaDistrict: 130130,
                offlineTime: 20,
                installMode: '固定',
                height: 45,
                intervalTime: 5,
                longitude: 114.96,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4196',
                establishDate: '2016-01-01',
                areaCity: 130100,
                ppeType: '当地',
                areaCode: 130130,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.7,
                deviceId: 23,
                deviceName: '赞皇县岭根底村',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/石家庄市/赞皇县',
                contact: '彭丽彬',
                areaDistrict: 130129,
                offlineTime: 20,
                installMode: '固定',
                height: 137,
                intervalTime: 5,
                longitude: 114.1875,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4184',
                establishDate: '2016-01-01',
                areaCity: 130100,
                ppeType: '当地',
                areaCode: 130129,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.35994,
                deviceId: 24,
                deviceName: '新乐市市承安铺',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/石家庄市/新乐市',
                contact: '彭丽彬',
                areaDistrict: 130184,
                offlineTime: 20,
                installMode: '固定',
                height: 71,
                intervalTime: 5,
                longitude: 114.6861,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4168',
                establishDate: '2016-01-01',
                areaCity: 130100,
                ppeType: '当地',
                areaCode: 130184,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.074,
                deviceId: 25,
                deviceName: '石家庄市鹿泉区',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/石家庄市/鹿泉区',
                contact: '彭丽彬',
                areaDistrict: 130110,
                offlineTime: 20,
                installMode: '固定',
                height: 94,
                intervalTime: 5,
                longitude: 114.316,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4173',
                establishDate: '2016-01-01',
                areaCity: 130100,
                ppeType: '当地',
                areaCode: 130110,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 41.852,
                deviceId: 26,
                deviceName: '康保县县1',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/张家口市/康保县',
                contact: '彭丽彬',
                areaDistrict: 130723,
                offlineTime: 20,
                installMode: '固定',
                height: 1422,
                intervalTime: 5,
                longitude: 114.602,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4082',
                establishDate: '2016-01-01',
                areaCity: 130700,
                ppeType: '当地',
                areaCode: 130723,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 41.85,
                deviceId: 27,
                deviceName: '康保县县2',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/张家口市/康保县',
                contact: '彭丽彬',
                areaDistrict: 130723,
                offlineTime: 20,
                installMode: '固定',
                height: 1422,
                intervalTime: 5,
                longitude: 114.602,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4131',
                establishDate: '2016-01-01',
                areaCity: 130700,
                ppeType: '当地',
                areaCode: 130723,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 41.64,
                deviceId: 28,
                deviceName: '张家口沽源县观测站',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/张家口市/沽源县',
                contact: '彭丽彬',
                areaDistrict: 130724,
                offlineTime: 20,
                installMode: '固定',
                height: 1412,
                intervalTime: 5,
                longitude: 115.65,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4045',
                establishDate: '2016-01-01',
                areaCity: 130700,
                ppeType: '当地',
                areaCode: 130724,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 41.095,
                deviceId: 29,
                deviceName: '张家口尚义县观测站',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/张家口市/尚义县',
                contact: '彭丽彬',
                areaDistrict: 130725,
                offlineTime: 20,
                installMode: '固定',
                height: 1377,
                intervalTime: 5,
                longitude: 113.986,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4043',
                establishDate: '2016-01-01',
                areaCity: 130700,
                ppeType: '当地',
                areaCode: 130725,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 40.336,
                deviceId: 30,
                deviceName: '怀来想长城葡萄酒炮点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/张家口市/怀来县',
                contact: '彭丽彬',
                areaDistrict: 130730,
                offlineTime: 20,
                installMode: '固定',
                height: 571,
                intervalTime: 5,
                longitude: 115.495,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4187',
                establishDate: '2016-01-01',
                areaCity: 130700,
                ppeType: '当地',
                areaCode: 130730,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 39.85,
                deviceId: 31,
                deviceName: '丰润区',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/唐山市/丰润区',
                contact: '彭丽彬',
                areaDistrict: 130208,
                offlineTime: 20,
                installMode: '固定',
                height: 33,
                intervalTime: 5,
                longitude: 118.186,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '3001',
                establishDate: '2016-01-01',
                areaCity: 130200,
                ppeType: '当地',
                areaCode: 130208,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 39.571,
                deviceId: 32,
                deviceName: '丰南区',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/唐山市/丰南区',
                contact: '彭丽彬',
                areaDistrict: 130207,
                offlineTime: 20,
                installMode: '固定',
                height: 9,
                intervalTime: 5,
                longitude: 118.056,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '3002',
                establishDate: '2016-01-01',
                areaCity: 130200,
                ppeType: '当地',
                areaCode: 130207,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 39.65,
                deviceId: 33,
                deviceName: '唐山市市西郊',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/唐山市/路北区',
                contact: '彭丽彬',
                areaDistrict: 130203,
                offlineTime: 20,
                installMode: '固定',
                height: 28,
                intervalTime: 5,
                longitude: 118.092,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4052',
                establishDate: '2016-01-01',
                areaCity: 130200,
                ppeType: '当地',
                areaCode: 130203,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 40.08,
                deviceId: 34,
                deviceName: '迁安市市',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/唐山市/迁安市',
                contact: '彭丽彬',
                areaDistrict: 130283,
                offlineTime: 20,
                installMode: '固定',
                height: 51,
                intervalTime: 5,
                longitude: 118.46,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4164',
                establishDate: '2016-01-01',
                areaCity: 130200,
                ppeType: '当地',
                areaCode: 130283,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.65,
                deviceId: 35,
                deviceName: '铁城作业点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/沧州市/吴桥县',
                contact: '彭丽彬',
                areaDistrict: 130928,
                offlineTime: 20,
                installMode: '固定',
                height: 17,
                intervalTime: 5,
                longitude: 116.48,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4024',
                establishDate: '2016-01-01',
                areaCity: 130900,
                ppeType: '当地',
                areaCode: 130928,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.83,
                deviceId: 36,
                deviceName: '大曹农场作业点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/沧州市/肃宁县',
                contact: '彭丽彬',
                areaDistrict: 130926,
                offlineTime: 20,
                installMode: '固定',
                height: 14,
                intervalTime: 5,
                longitude: 116.62,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4077',
                establishDate: '2016-01-01',
                areaCity: 130900,
                ppeType: '当地',
                areaCode: 130926,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.04,
                deviceId: 37,
                deviceName: '盐山县大韩村',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/沧州市/盐山县',
                contact: '彭丽彬',
                areaDistrict: 130925,
                offlineTime: 20,
                installMode: '固定',
                height: 8,
                intervalTime: 5,
                longitude: 117.17,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4097',
                establishDate: '2016-01-01',
                areaCity: 130900,
                ppeType: '当地',
                areaCode: 130925,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.93,
                deviceId: 38,
                deviceName: '潞灌乡作业点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/沧州市/南皮县',
                contact: '彭丽彬',
                areaDistrict: 130927,
                offlineTime: 20,
                installMode: '固定',
                height: 11,
                intervalTime: 5,
                longitude: 116.96,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4099',
                establishDate: '2016-01-01',
                areaCity: 130900,
                ppeType: '当地',
                areaCode: 130927,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.03,
                deviceId: 39,
                deviceName: '宋庄子乡作业点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/沧州市/',
                contact: '彭丽彬',
                areaDistrict: 0,
                offlineTime: 20,
                installMode: '固定',
                height: 11,
                intervalTime: 5,
                longitude: 117.06,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4017',
                establishDate: '2016-01-01',
                areaCity: 130900,
                ppeType: '当地',
                areaCode: 0,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.14,
                deviceId: 40,
                deviceName: '齐桥作业点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/沧州市/泊头市',
                contact: '彭丽彬',
                areaDistrict: 130981,
                offlineTime: 20,
                installMode: '固定',
                height: 13,
                intervalTime: 5,
                longitude: 116.49,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4118',
                establishDate: '2016-01-01',
                areaCity: 130900,
                ppeType: '当地',
                areaCode: 130981,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.11,
                deviceId: 41,
                deviceName: '辛集镇作业点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/沧州市/海兴县',
                contact: '彭丽彬',
                areaDistrict: 130924,
                offlineTime: 20,
                installMode: '固定',
                height: 6,
                intervalTime: 5,
                longitude: 117.59,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4108',
                establishDate: '2016-01-01',
                areaCity: 130900,
                ppeType: '当地',
                areaCode: 130924,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.28,
                deviceId: 42,
                deviceName: '献县陌南乡',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/沧州市/献县',
                contact: '彭丽彬',
                areaDistrict: 130929,
                offlineTime: 20,
                installMode: '固定',
                height: 13,
                intervalTime: 5,
                longitude: 115.87967,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4028',
                establishDate: '2016-01-01',
                areaCity: 130900,
                ppeType: '当地',
                areaCode: 130929,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.4,
                deviceId: 43,
                deviceName: '中捷农场作业点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/沧州市/黄骅市',
                contact: '彭丽彬',
                areaDistrict: 130983,
                offlineTime: 20,
                installMode: '固定',
                height: 9,
                intervalTime: 5,
                longitude: 117.52,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4140',
                establishDate: '2016-01-01',
                areaCity: 130900,
                ppeType: '当地',
                areaCode: 130983,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.42,
                deviceId: 44,
                deviceName: '故仙乡作业点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/沧州市/河间市',
                contact: '彭丽彬',
                areaDistrict: 130984,
                offlineTime: 20,
                installMode: '固定',
                height: 11,
                intervalTime: 5,
                longitude: 116.39,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4141',
                establishDate: '2016-01-01',
                areaCity: 130900,
                ppeType: '当地',
                areaCode: 130984,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.4,
                deviceId: 45,
                deviceName: '滕庄子作业点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/沧州市/黄骅市',
                contact: '彭丽彬',
                areaDistrict: 130983,
                offlineTime: 20,
                installMode: '固定',
                height: 7,
                intervalTime: 5,
                longitude: 117.16,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4136',
                establishDate: '2016-01-01',
                areaCity: 130900,
                ppeType: '当地',
                areaCode: 130983,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.51,
                deviceId: 46,
                deviceName: '西村乡作业点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/沧州市/河间市',
                contact: '彭丽彬',
                areaDistrict: 130984,
                offlineTime: 20,
                installMode: '固定',
                height: 11,
                intervalTime: 5,
                longitude: 116.07,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4145',
                establishDate: '2016-01-01',
                areaCity: 130900,
                ppeType: '当地',
                areaCode: 130984,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.4,
                deviceId: 47,
                deviceName: '训练基地作业点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/沧州市/肃宁县',
                contact: '彭丽彬',
                areaDistrict: 130926,
                offlineTime: 20,
                installMode: '固定',
                height: 5,
                intervalTime: 5,
                longitude: 115.85,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4026',
                establishDate: '2016-01-01',
                areaCity: 130900,
                ppeType: '当地',
                areaCode: 130926,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.38,
                deviceId: 48,
                deviceName: '陆官屯作业点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/沧州市/沧县',
                contact: '彭丽彬',
                areaDistrict: 130921,
                offlineTime: 20,
                installMode: '固定',
                height: 11,
                intervalTime: 5,
                longitude: 116.5,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4089',
                establishDate: '2016-01-01',
                areaCity: 130900,
                ppeType: '当地',
                areaCode: 130921,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.75,
                deviceId: 49,
                deviceName: '议论堡作业点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/沧州市/任丘市',
                contact: '彭丽彬',
                areaDistrict: 130982,
                offlineTime: 20,
                installMode: '固定',
                height: 8,
                intervalTime: 5,
                longitude: 116.19,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4093',
                establishDate: '2016-01-01',
                areaCity: 130900,
                ppeType: '当地',
                areaCode: 130982,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.25722,
                deviceId: 50,
                deviceName: '东大洼炮点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/衡水市/故城县',
                contact: '彭丽彬',
                areaDistrict: 131126,
                offlineTime: 20,
                installMode: '固定',
                height: 27,
                intervalTime: 5,
                longitude: 115.9,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4134',
                establishDate: '2016-01-01',
                areaCity: 131100,
                ppeType: '当地',
                areaCode: 131126,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.56,
                deviceId: 51,
                deviceName: '枣强欣苑',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/衡水市/枣强县',
                contact: '彭丽彬',
                areaDistrict: 131121,
                offlineTime: 20,
                installMode: '固定',
                height: 24,
                intervalTime: 5,
                longitude: 115.8,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4142',
                establishDate: '2016-01-01',
                areaCity: 131100,
                ppeType: '当地',
                areaCode: 131121,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.512,
                deviceId: 52,
                deviceName: '冀州区',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/衡水市/冀州区',
                contact: '彭丽彬',
                areaDistrict: 131103,
                offlineTime: 20,
                installMode: '固定',
                height: 35,
                intervalTime: 5,
                longitude: 115.53,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4124',
                establishDate: '2016-01-01',
                areaCity: 131100,
                ppeType: '当地',
                areaCode: 131103,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.61,
                deviceId: 53,
                deviceName: '津龙公司作业点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/衡水市/景县',
                contact: '彭丽彬',
                areaDistrict: 131127,
                offlineTime: 20,
                installMode: '固定',
                height: 18,
                intervalTime: 5,
                longitude: 116.01,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4144',
                establishDate: '2016-01-01',
                areaCity: 131100,
                ppeType: '当地',
                areaCode: 131127,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.45,
                deviceId: 54,
                deviceName: '故城三郎',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/衡水市/故城县',
                contact: '彭丽彬',
                areaDistrict: 131126,
                offlineTime: 20,
                installMode: '固定',
                height: 27,
                intervalTime: 5,
                longitude: 115.89,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4139',
                establishDate: '2016-01-01',
                areaCity: 131100,
                ppeType: '当地',
                areaCode: 131126,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.85889,
                deviceId: 55,
                deviceName: '武邑圈头作业点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/衡水市/武邑县',
                contact: '彭丽彬',
                areaDistrict: 131122,
                offlineTime: 20,
                installMode: '固定',
                height: 21,
                intervalTime: 5,
                longitude: 115.81,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4079',
                establishDate: '2016-01-01',
                areaCity: 131100,
                ppeType: '当地',
                areaCode: 131122,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.846,
                deviceId: 56,
                deviceName: '阜城',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/衡水市/阜城县',
                contact: '彭丽彬',
                areaDistrict: 131128,
                offlineTime: 20,
                installMode: '固定',
                height: 19,
                intervalTime: 5,
                longitude: 116.16,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4015',
                establishDate: '2016-01-01',
                areaCity: 131100,
                ppeType: '当地',
                areaCode: 131128,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.03,
                deviceId: 57,
                deviceName: '武强镇作业点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/衡水市/武强县',
                contact: '彭丽彬',
                areaDistrict: 131123,
                offlineTime: 20,
                installMode: '固定',
                height: 16,
                intervalTime: 5,
                longitude: 115.93,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4135',
                establishDate: '2016-01-01',
                areaCity: 131100,
                ppeType: '当地',
                areaCode: 131123,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.03499,
                deviceId: 58,
                deviceName: '穆村炮点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/衡水市/深州市',
                contact: '彭丽彬',
                areaDistrict: 131182,
                offlineTime: 20,
                installMode: '固定',
                height: 26,
                intervalTime: 5,
                longitude: 115.51999,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '3005',
                establishDate: '2016-01-01',
                areaCity: 131100,
                ppeType: '当地',
                areaCode: 131182,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.12,
                deviceId: 59,
                deviceName: '唐奉作业点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/衡水市/深州市',
                contact: '彭丽彬',
                areaDistrict: 131182,
                offlineTime: 20,
                installMode: '固定',
                height: 26,
                intervalTime: 5,
                longitude: 115.51,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4137',
                establishDate: '2016-01-01',
                areaCity: 131100,
                ppeType: '当地',
                areaCode: 131182,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.25,
                deviceId: 60,
                deviceName: '饶阳县南京堂作业点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/衡水市/饶阳县',
                contact: '彭丽彬',
                areaDistrict: 131124,
                offlineTime: 20,
                installMode: '固定',
                height: 19,
                intervalTime: 5,
                longitude: 115.76,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '3062',
                establishDate: '2016-01-01',
                areaCity: 131100,
                ppeType: '当地',
                areaCode: 131124,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.27,
                deviceId: 61,
                deviceName: '安平',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/衡水市/安平县',
                contact: '彭丽彬',
                areaDistrict: 131125,
                offlineTime: 20,
                installMode: '固定',
                height: 26,
                intervalTime: 5,
                longitude: 115.56,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4253',
                establishDate: '2016-01-01',
                areaCity: 131100,
                ppeType: '当地',
                areaCode: 131125,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 38.23,
                deviceId: 62,
                deviceName: '五公镇作业点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/衡水市/',
                contact: '彭丽彬',
                areaDistrict: 0,
                offlineTime: 20,
                installMode: '固定',
                height: 26,
                intervalTime: 5,
                longitude: 115.73,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4133',
                establishDate: '2016-01-01',
                areaCity: 131100,
                ppeType: '当地',
                areaCode: 0,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.33,
                deviceId: 63,
                deviceName: '岗底',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邢台市/内丘县',
                contact: '彭丽彬',
                areaDistrict: 130523,
                offlineTime: 20,
                installMode: '固定',
                height: 575,
                intervalTime: 5,
                longitude: 114.09,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '3050',
                establishDate: '2016-01-01',
                areaCity: 130500,
                ppeType: '当地',
                areaCode: 130523,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 36.901,
                deviceId: 64,
                deviceName: '沙河利多生态园炮点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邢台市/沙河市',
                contact: '彭丽彬',
                areaDistrict: 130582,
                offlineTime: 20,
                installMode: '固定',
                height: 68,
                intervalTime: 5,
                longitude: 114.4,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4146',
                establishDate: '2016-01-01',
                areaCity: 130500,
                ppeType: '当地',
                areaCode: 130582,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.072,
                deviceId: 65,
                deviceName: '城计头炮点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邢台市/邢台县',
                contact: '彭丽彬',
                areaDistrict: 130521,
                offlineTime: 20,
                installMode: '固定',
                height: 77,
                intervalTime: 5,
                longitude: 114.057,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4094',
                establishDate: '2016-01-01',
                areaCity: 130500,
                ppeType: '当地',
                areaCode: 130521,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.17,
                deviceId: 66,
                deviceName: '浆水镇 ',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邢台市/邢台县',
                contact: '彭丽彬',
                areaDistrict: 130521,
                offlineTime: 20,
                installMode: '固定',
                height: 77,
                intervalTime: 5,
                longitude: 113.95,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4073',
                establishDate: '2016-01-01',
                areaCity: 130500,
                ppeType: '当地',
                areaCode: 130521,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.02,
                deviceId: 67,
                deviceName: '花木村',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邢台市/沙河市',
                contact: '彭丽彬',
                areaDistrict: 130582,
                offlineTime: 20,
                installMode: '固定',
                height: 68,
                intervalTime: 5,
                longitude: 113.94,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4036',
                establishDate: '2016-01-01',
                areaCity: 130500,
                ppeType: '当地',
                areaCode: 130582,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.129,
                deviceId: 68,
                deviceName: '后刘庄炮点',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邢台市/平乡县',
                contact: '彭丽彬',
                areaDistrict: 130532,
                offlineTime: 20,
                installMode: '固定',
                height: 34,
                intervalTime: 5,
                longitude: 114.91,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4109',
                establishDate: '2016-01-01',
                areaCity: 130500,
                ppeType: '当地',
                areaCode: 130532,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.36,
                deviceId: 69,
                deviceName: '官厅镇',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邢台市/巨鹿县',
                contact: '彭丽彬',
                areaDistrict: 130529,
                offlineTime: 20,
                installMode: '固定',
                height: 26,
                intervalTime: 5,
                longitude: 115.07,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4018',
                establishDate: '2016-01-01',
                areaCity: 130500,
                ppeType: '当地',
                areaCode: 130529,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.29,
                deviceId: 70,
                deviceName: '内丘县',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邢台市/内丘县',
                contact: '彭丽彬',
                areaDistrict: 130523,
                offlineTime: 20,
                installMode: '固定',
                height: 87,
                intervalTime: 5,
                longitude: 114.52,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '3069',
                establishDate: '2016-01-01',
                areaCity: 130500,
                ppeType: '当地',
                areaCode: 130523,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.36,
                deviceId: 71,
                deviceName: '西侯村',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邢台市/隆尧县',
                contact: '彭丽彬',
                areaDistrict: 130525,
                offlineTime: 20,
                installMode: '固定',
                height: 33,
                intervalTime: 5,
                longitude: 114.67,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '3025',
                establishDate: '2016-01-01',
                areaCity: 130500,
                ppeType: '当地',
                areaCode: 130525,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.37,
                deviceId: 72,
                deviceName: '贾侍郎',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邢台市/南宫市',
                contact: '彭丽彬',
                areaDistrict: 130581,
                offlineTime: 20,
                installMode: '固定',
                height: 27,
                intervalTime: 5,
                longitude: 115.25,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4143',
                establishDate: '2016-01-01',
                areaCity: 130500,
                ppeType: '当地',
                areaCode: 130581,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.51,
                deviceId: 73,
                deviceName: '临城绿岭',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邢台市/临城县',
                contact: '彭丽彬',
                areaDistrict: 130522,
                offlineTime: 20,
                installMode: '固定',
                height: 113,
                intervalTime: 5,
                longitude: 114.54,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '3021',
                establishDate: '2016-01-01',
                areaCity: 130500,
                ppeType: '当地',
                areaCode: 130522,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.07,
                deviceId: 74,
                deviceName: '市局',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邢台市/桥西区',
                contact: '彭丽彬',
                areaDistrict: 130503,
                offlineTime: 20,
                installMode: '固定',
                height: 85,
                intervalTime: 5,
                longitude: 114.48,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4088',
                establishDate: '2016-01-01',
                areaCity: 130500,
                ppeType: '当地',
                areaCode: 130503,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 37.58,
                deviceId: 75,
                deviceName: '东王里',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邢台市/宁晋县',
                contact: '彭丽彬',
                areaDistrict: 130528,
                offlineTime: 20,
                installMode: '固定',
                height: 31,
                intervalTime: 5,
                longitude: 114.93,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '4091',
                establishDate: '2016-01-01',
                areaCity: 130500,
                ppeType: '当地',
                areaCode: 130528,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
            {
                deviceTypeId: 1,
                loseTime: 20,
                latitude: 39.93,
                deviceId: 76,
                deviceName: '秦皇岛雨滴谱仪',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/秦皇岛市/海港区',
                contact: '彭丽彬',
                areaDistrict: 130302,
                offlineTime: 20,
                installMode: '固定',
                height: 18,
                intervalTime: 5,
                longitude: 119.6,
                deviceTypeName: '雨滴谱仪',
                factoryName: '江西新余国科科技有限公司',
                telephone: '17307906001',
                deviceCode: '3003',
                establishDate: '2016-01-01',
                areaCity: 130300,
                ppeType: '当地',
                areaCode: 130302,
                establishCompany: '省人影办',
                deviceModel: 'OTT Parsivel2',
            },
        ],
        legend: '1',
    },
    {
        deviceType: '微波辐射计',
        deviceTypeId: 2,
        devices: [
            {
                deviceTypeId: 2,
                loseTime: 20,
                latitude: 37.90370774,
                deviceId: 77,
                deviceName: '栾城区人影基地',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/石家庄市/栾城区',
                contact: '郭臣',
                areaDistrict: 130111,
                offlineTime: 20,
                installMode: '固定',
                height: 52,
                intervalTime: 5,
                longitude: 114.60973078,
                deviceTypeName: '微波辐射计',
                factoryName: '杭州浅海科技有限公司',
                telephone: '18502250086',
                deviceCode: '53789',
                establishDate: '2016-01-01',
                areaCity: 130100,
                ppeType: '省人影办',
                areaCode: 130111,
                establishCompany: '省人影办',
                deviceModel: 'MWP3000',
            },
            {
                deviceTypeId: 2,
                loseTime: 20,
                latitude: 37.71694,
                deviceId: 78,
                deviceName: '衡水市气象局',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省//桃城区',
                contact: '赵新玲',
                areaDistrict: 131102,
                offlineTime: 20,
                installMode: '固定',
                height: 36,
                intervalTime: 5,
                longitude: 115.711111,
                deviceTypeName: '微波辐射计',
                factoryName: '西安电子工程研究所',
                telephone: '15829640945',
                deviceCode: '54702',
                establishDate: '2016-01-01',
                areaCity: 0,
                ppeType: '省人影办',
                areaCode: 131102,
                establishCompany: '省人影办',
                deviceModel: 'MWP967KV',
            },
            {
                deviceTypeId: 2,
                loseTime: 20,
                latitude: 37.17551486,
                deviceId: 79,
                deviceName: '邢台市皇寺',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邢台市/邢台县',
                contact: '赵新玲',
                areaDistrict: 130521,
                offlineTime: 20,
                installMode: '固定',
                height: 168,
                intervalTime: 5,
                longitude: 114.35814134,
                deviceTypeName: '微波辐射计',
                factoryName: '西安电子工程研究所',
                telephone: '15829640945',
                deviceCode: '53798',
                establishDate: '2016-01-01',
                areaCity: 130500,
                ppeType: '省人影办',
                areaCode: 130521,
                establishCompany: '省人影办',
                deviceModel: 'MWP967KV',
            },
        ],
        legend: '1',
    },
    {
        deviceType: '微雨雷达',
        deviceTypeId: 3,
        devices: [
            {
                deviceTypeId: 3,
                loseTime: 20,
                latitude: 37.17551486,
                deviceId: 80,
                deviceName: '邢台市皇寺',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邢台市/邢台县',
                contact: '郭臣',
                areaDistrict: 130521,
                offlineTime: 20,
                installMode: '固定',
                height: 168,
                intervalTime: 5,
                longitude: 114.35814134,
                deviceTypeName: '微雨雷达',
                factoryName: '杭州浅海科技有限公司',
                telephone: '18502250086',
                deviceCode: '53798',
                establishDate: '2016-05-01',
                areaCity: 130500,
                ppeType: '省人影办',
                areaCode: 130521,
                establishCompany: '省人影办',
                deviceModel: 'METEK',
            },
            {
                deviceTypeId: 3,
                loseTime: 20,
                latitude: 37.90370774,
                deviceId: 81,
                deviceName: '栾城区人影基地',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/石家庄市/栾城区',
                contact: '郭臣',
                areaDistrict: 130111,
                offlineTime: 20,
                installMode: '固定',
                height: 52,
                intervalTime: 5,
                longitude: 114.60973078,
                deviceTypeName: '微雨雷达',
                factoryName: '杭州浅海科技有限公司',
                telephone: '18502250086',
                deviceCode: '53789',
                establishDate: '2016-05-01',
                areaCity: 130100,
                ppeType: '省人影办',
                areaCode: 130111,
                establishCompany: '省人影办',
                deviceModel: 'METEK',
            },
        ],
        legend: '1',
    },
    { deviceType: '激光云高仪', deviceTypeId: 4, devices: [], legend: '1' },
    {
        deviceType: 'Ka波段测云仪',
        deviceTypeId: 5,
        devices: [
            {
                deviceTypeId: 5,
                loseTime: 20,
                latitude: 37.17551486,
                deviceId: 82,
                deviceName: '邢台市皇寺',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邢台市/邢台县',
                contact: '李毅',
                areaDistrict: 130521,
                offlineTime: 20,
                installMode: '固定',
                height: 168,
                intervalTime: 5,
                longitude: 114.35814134,
                deviceTypeName: 'Ka波段测云仪',
                factoryName: '华腾微波',
                telephone: '18729349254',
                deviceCode: '53798',
                establishDate: '2017-04-01',
                areaCity: 130500,
                ppeType: '省人影办',
                areaCode: 130521,
                establishCompany: '省人影办',
                deviceModel: 'HT101型',
            },
            {
                deviceTypeId: 5,
                loseTime: 20,
                latitude: 37.90370774,
                deviceId: 83,
                deviceName: '栾城区人影基地',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/石家庄市/栾城区',
                contact: '李毅',
                areaDistrict: 130111,
                offlineTime: 20,
                installMode: '固定',
                height: 52,
                intervalTime: 5,
                longitude: 114.60973078,
                deviceTypeName: 'Ka波段测云仪',
                factoryName: '华腾微波',
                telephone: '18729349254',
                deviceCode: '53789',
                establishDate: '2017-05-01',
                areaCity: 130100,
                ppeType: '省人影办',
                areaCode: 130111,
                establishCompany: '省人影办',
                deviceModel: 'HT101型',
            },
            {
                deviceTypeId: 5,
                loseTime: 20,
                latitude: 40.76981375,
                deviceId: 84,
                deviceName: '冀西北基地(张家口市国家高空气象站)',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/张家口市/桥东区',
                contact: '李毅',
                areaDistrict: 130702,
                offlineTime: 20,
                installMode: '固定',
                height: 767,
                intervalTime: 5,
                longitude: 114.91898497,
                deviceTypeName: 'Ka波段测云仪',
                factoryName: '华腾微波',
                telephone: '18729349254',
                deviceCode: '54401',
                establishDate: '2017-06-01',
                areaCity: 130700,
                ppeType: '省人影办',
                areaCode: 130702,
                establishCompany: '省人影办',
                deviceModel: 'HT101型',
            },
        ],
        legend: '1',
    },
    {
        deviceType: '气象雷达',
        deviceTypeId: 6,
        devices: [
            {
                deviceTypeId: 6,
                loseTime: 20,
                latitude: 37.80561,
                deviceId: 85,
                deviceName: '元氏县观测站',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/石家庄市/元氏县',
                contact: '陈超',
                areaDistrict: 130132,
                offlineTime: 20,
                installMode: '车载',
                height: 67,
                intervalTime: 5,
                longitude: 114.49924,
                deviceTypeName: '气象雷达',
                factoryName: '中船重工鹏力(南京)大气海洋信息系统有限公司',
                telephone: '13815801335',
                deviceCode: '53791',
                establishDate: '2017-05-01',
                areaCity: 130100,
                ppeType: '省人影办',
                areaCode: 130132,
                establishCompany: '省人影办',
                deviceModel: '724XSP',
            },
            {
                deviceTypeId: 6,
                loseTime: 20,
                latitude: 38.22306,
                deviceId: 86,
                deviceName: '饶阳县气象局',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省//饶阳县',
                contact: '陈超',
                areaDistrict: 131124,
                offlineTime: 20,
                installMode: '固定',
                height: 33,
                intervalTime: 5,
                longitude: 115.74306,
                deviceTypeName: '气象雷达',
                factoryName: '中船重工鹏力(南京)大气海洋信息系统有限公司',
                telephone: '13815801335',
                deviceCode: '54606',
                establishDate: '2017-05-01',
                areaCity: 0,
                ppeType: '当地',
                areaCode: 131124,
                establishCompany: '省人影办',
                deviceModel: '724XSP',
            },
            {
                deviceTypeId: 6,
                loseTime: 20,
                latitude: 37.29056,
                deviceId: 87,
                deviceName: '内丘县气象局',
                areaProvince: 130000,
                mapLevel: 7,
                areaName: '河北省/邢台市/内丘县',
                contact: '陈超',
                areaDistrict: 130523,
                offlineTime: 20,
                installMode: '车载',
                height: 173,
                intervalTime: 5,
                longitude: 114.38667,
                deviceTypeName: '气象雷达',
                factoryName: '中船重工鹏力(南京)大气海洋信息系统有限公司',
                telephone: '13815801335',
                deviceCode: '53797',
                establishDate: '2017-05-01',
                areaCity: 130500,
                ppeType: '当地',
                areaCode: 130523,
                establishCompany: '省人影办',
                deviceModel: '724XSP',
            },
        ],
        legend: '1',
    },
]
