const icons = {
    temperature: {
        name: '气温',
        icon: require('../../../assets/images/operation/normal/qiwen.png'),
        'icon-e': require('../../../assets/images/operation/error/qiwen.png'),
        company: '℃',
    }, //温度
    humidity: {
        name: '湿度',
        icon: require('../../../assets/images/operation/normal/shidu.png'),
        'icon-e': require('../../../assets/images/operation/error/shidu.png'),
        company: '%',
    }, //湿度
    pressure: {
        name: '气压',
        icon: require('../../../assets/images/operation/normal/qiya.png'),
        'icon-e': require('../../../assets/images/operation/error/qiya.png'),
        company: 'hpa',
    }, //湿度
    windSpeed: {
        name: '风速',
        icon: require('../../../assets/images/operation/normal/fengsu.png'),
        'icon-e': require('../../../assets/images/operation/error/fengsu.png'),
        company: 'm/s',
    }, //风速
    windDirection: {
        name: '风向',
        icon: require('../../../assets/images/operation/normal/fengxiang.png'),
        'icon-e': require('../../../assets/images/operation/error/fengxiang.png'),
    }, //风向
    uv: {
        name: '紫外线指数',
        icon: require('../../../assets/images/operation/normal/uv.png'),
        'icon-e': require('../../../assets/images/operation/error/uv.png'),
    }, //紫外线
    chaoxi: {
        name: '潮汐',
        icon: require('../../../assets/images/operation/normal/chaoxi.png'),
        'icon-e': require('../../../assets/images/operation/error/chaoxi.png'),
    }, //潮汐
    dianya: {
        name: '电压',
        icon: require('../../../assets/images/operation/normal/dianya.png'),
        'icon-e': require('../../../assets/images/operation/error/dianya.png'),
    }, //电压
    fengxiangfengshu: {
        name: '风向风速',
        icon: require('../../../assets/images/operation/normal/fengxiangfengsu.png'),
        'icon-e': require('../../../assets/images/operation/error/fengxiangfengsu.png'),
    }, //风向风速
    jiangyu: {
        name: '降雨',
        icon: require('../../../assets/images/operation/normal/jiangyu.png'),
        'icon-e': require('../../../assets/images/operation/error/jiangyu.png'),
    }, //降雨
    langgao: {
        name: '浪高',
        icon: require('../../../assets/images/operation/normal/langgao.png'),
        'icon-e': require('../../../assets/images/operation/error/langgao.png'),
    }, //浪高
    monifengxiang: {
        name: '模拟风向',
        icon: require('../../../assets/images/operation/normal/monifengxiang.png'),
        'icon-e': require('../../../assets/images/operation/error/monifengxiang.png'),
    }, //模拟风向
    rongyangdu: {
        name: '溶氧度',
        icon: require('../../../assets/images/operation/normal/rongyangdu.png'),
        'icon-e': require('../../../assets/images/operation/error/rongyangdu.png'),
    }, //溶氧度
    taiyangfushe: {
        name: '太阳辐射',
        icon: require('../../../assets/images/operation/normal/taiyangfushe.png'),
        'icon-e': require('../../../assets/images/operation/error/taiyangfushe.png'),
    }, //太阳辐射
    turangshidu: {
        name: '',
        icon: require('../../../assets/images/operation/normal/turangshidu.png'),
        'icon-e': require('../../../assets/images/operation/error/turangshidu.png'),
    }, //土壤湿度
    zhengfa: {
        name: '蒸发量',
        icon: require('../../../assets/images/operation/normal/zhengfa.png'),
        'icon-e': require('../../../assets/images/operation/error/zhengfa.png'),
    }, //蒸发量
}
export default icons
